language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

services: 
  - mysql

mysql:
  database: wp_bebop
  username: root
  encoding: utf8

env:
  global:
  matrix:
    - WORDPRESS_VERSION=3.5.2
    - WORDPRESS_VERSION=3.9

before_install:

  # Update testing machine
  - sudo apt-get update -qq
  - sudo apt-get install -qq

install: composer install

before_script:

  # Start built-in PHP server (PHP >= 5.4)
  - php -S 127.0.0.1:4000 -t ./wp-core &

  # Create database
  - mysql -e 'create database wp_bebop'

  # Install WordPress
  - source ./ci/install-wordpress.sh $WORDPRESS_VERSION

  # Setup testing theme
  - source ./ci/setup-theme.sh

script: ./vendor/bin/codecept run