language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

services: 
  - mysql

mysql:
  database: wp_bebop
  username: root
  encoding: utf8

env:
  global:
  matrix:
    - WORDPRESS_VERSION=3.5.2
    - WORDPRESS_VERSION=3.9

before_install:

  # Update testing machine
  - sudo apt-get update -qq
  - sudo apt-get install -qq

  # Install Java and PhantomJS
  - sudo apt-get install -y default-jre phantomjs
  - java -version
  - phantomjs -v

  # Install and run Selenium WebDriver
  - wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar
  - java -jar selenium-server-standalone-2.41.0.jar &

install: composer install -o --no-interaction

before_script:

  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  
  # configure apache virtual hosts
  - sudo cp -f ci/apache.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  # Create database
  - mysql -e 'create database wp_bebop'

  # Install WordPress
  - source ./ci/install-wordpress.sh $WORDPRESS_VERSION

  # Setup testing theme
  - source ./ci/setup-theme.sh

script: ./vendor/bin/codecept run